name: Checks

on:
  pull_request:
    branches: main

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ inputs.github-token }}

      - name: Set up Docker Buildx for Docker build caching
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ inputs.repo_name }}/${{ inputs.project_name }}:latest

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ inputs.github-token }}

      - name: Run tests
        run: make test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ inputs.github-token }}

      - name: Check linting
        run: make lint