name: 'Docker build and push'
description: 'Build and push Docker image to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry'
    default: ghcr.io
  repository:
    description: 'Repository name'
    required: true
  version:
    description: 'Version tag'
    default: latest
runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
          echo "registry=${{ inputs.registry }}"
          echo "repository=${{ inputs.repository }}"
          echo "version=${{ inputs.version }}"
    - name: Docker pull
      shell: bash
      run: make pull
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        VERSION: ${{ inputs.version }}
    - name: Docker build
      shell: bash
      run: make build
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        VERSION: ${{ inputs.version }}
    - name: Docker push
      shell: bash
      run: make push
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        VERSION: ${{ inputs.version }}