name: 'Docker build and push'
description: 'Build and push Docker image to GitHub Container Registry'

runs:
  using: "composite"
  steps:
    - name: Set up Docker build caching
      uses: docker/setup-buildx-action@v2
    - name: Lowercase repository name
      id: repo
      uses: ASzc/change-string-case-action@v5
      with:
        string: github.repository
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{ steps.repo.outputs.lowercase }}:latest