name: 'Docker build and push'
description: 'Build and push Docker image to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry'
    default: ghcr.io
  repository:
    description: 'Repository name'
    required: true
  version:
    description: 'Version tag'
    default: latest
runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
          echo "registry=${{ inputs.registry }}"
          echo "repository=${{ github.repository_owner }}/${{ inputs.repository }}" 
          echo "repository=${{ github.repository_owner }}/${{ inputs.repository }}" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.version }}"
    - name: Docker build
      shell: bash
      run: REGISTRY=${{ inputs.registry }} REPOSITORY=${{ steps.variables.outputs.repository }} VERSION=${{ inputs.version }} make build
    - name: Docker push
      shell: bash
      run: REGISTRY=${{ inputs.registry }} REPOSITORY=${{ steps.variables.outputs.repository }} VERSION=${{ inputs.version }} make push