name: 'Slack Message'
description: 'Send a message to Slack'

inputs:
  token:
    description: 'Slack token'
    required: true
  channel:
    description: 'Slack channel'
    required: true
  message:
    description: 'Message to send'
    required: true
  pr-url:
    description: 'Pull request url'
    required: true
  release-url:
    description: 'Release url'
    required: true
  acceptance-pipeline:
    description: 'Acceptance pipeline'
  production-pipeline:
    description: 'Production pipeline'
  acceptance-urls:
    description: 'Acceptance urls'
  production-urls:
    description: 'Production urls'
  timetell-code:
    description: 'Timetell code'

runs:
  using: "composite"
  steps:
    - name: Send Slack Message
      uses: archive/github-actions-slack@master
      id: send-message
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ inputs.token }}
        slack-channel: ${{ inputs.channel }}
        slack-text: ${{ inputs.message }}

    - name: Send "Slack Message" Result
      shell: bash
      id: send-result
      run: |
        echo "Data - ${{ steps.send-message.outputs.slack-result }}"
        echo "thread_ts=${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}" >> $GITHUB_OUTPUT

    - name: Thread message 1
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ inputs.token }}
        slack-channel: ${{ inputs.slack_channel }}
        slack-optional-thread_ts: ${{ steps.send-result.outputs.thread_ts }}
        slack-text: 1. Review Pull Request "${{inputs.pr_url}}"
        slack-optional-icon_emoji: ":eyes:"

    - name: Thread message 2
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ inputs.token }}
        slack-channel: ${{ inputs.slack_channel }}
        slack-optional-thread_ts: ${{ steps.send-result.outputs.thread_ts }}
        slack-text: 2. Release Naar Acceptatie (merge naar master) "${{ inputs.pr_url }}"
        slack-optional-icon_emoji: ":twisted_rightwards_arrows:"

#        if [ -n "${{ inputs.acceptance_pipeline }}" ]; then
#          echo "3. Controleer Acceptatie Deployment Job ${{ inputs.acceptance_pipeline }} :jenkins-acc:"
#        fi
#        if [ -n "${{ inputs.acceptance_urls }}" ]; then
#          echo "4. Controleer Acceptatie \n${{ inputs.acceptance_urls }} :release-acc:"
#        fi
#        echo "5. Release Naar Productie (tag versie) ${{ steps.variables.outputs.release_url }} :label:"
#
#        if [ -n "${{ inputs.production_pipeline }}" ]; then
#          echo "6. Controleer Productie Deployment Job ${{ inputs.production_pipeline }} :jenkins_ci:"
#        fi
#        if [ -n "${{ inputs.production_urls }}" ]; then
#          echo "7. Controleer Productie \n${{ inputs.production_urls }} :rocket:"
#        fi
#        if [ -n "${{ inputs.timetell }}" ]; then
#          echo "8. Timetell code: ${{ inputs.timetell }} :clock1:"
#        fi