name: 'GitHub Container Registry Login'
description: 'Checks out the repository and logs in to GitHub Container Registry'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout backend
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
#        registry: <registry-name>.azurecr.io
#        username: ${{ secrets.AZURE_CLIENT_ID }}
#        password: ${{ secrets.AZURE_CLIENT_SECRET }}
