name: 'GitHub Container Registry Login'
description: 'Checks out the repository and logs in to GitHub Container Registry'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  branch:
    description: 'Checkout ref (branch or commit)'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
