name: CI Checks

on:
  workflow_call:

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push to GHCR
        uses: amsterdam/github-workflows/build-and-push@v1

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check linting
        run: make lint