name: CI Checks

on:
  pull_request:
    branches: main
  workflow_call:
    inputs:
      repo_name:
        description: 'Repository name'
        type: string
        default: 'amsterdam'
      project_name:
        description: 'Project name'
        required: true
        type: string
      docker_files:
        description: 'Docker files'
        required: true
        type: string
        default: '["Dockerfile"]'

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromArray(input.docker_files) }}
          inputs.docker_files }}
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx for Docker build caching
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: ${{ matrix.value }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ inputs.repo_name }}/${{ inputs.project_name }}:latest

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: make test

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Login to GitHub Container Registry
        uses: amsterdam/opdrachten-team-github-workflows/ghcr-login@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check linting
        run: make lint