name: Opdrachten Team Dependabot

on:
  workflow_call:
    inputs:
      default_branch:
        description: 'Default branch'
        type: string
        default: 'main'
      slack_channel:
        description: 'Slack channel'
        type: string
        required: true

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default_branch }}

#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Update dependencies file
#      run: make requirements
#
#    - name: Set up Docker build caching
#      uses: docker/setup-buildx-action@v2
#
#    - name: Build with updated dependencies and push
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: true
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
#        tags: ghcr.io/amsterdam/meetbouten:latest
#
#    - name: Run Tests
#      run: make test

    - name: Get current date
      id: date
      run: echo "today=$(date +'%Y-%m-%d')" >>  $GITHUB_OUTPUT

    - name: Print current date
      run: echo "Today is ${{ steps.date.outputs.today }}"

#    - name: Create Pull Request
#      uses: peter-evans/create-pull-request@v5
#      with:
#        title: 'Maintenance run ${{ steps.date.outputs.today }}'
#        labels: Opdrachten Team Dependabot
#        body: |
#          Auto generated PR to update dependencies.
#          This PR is generated by the Opdrachten Team Dependabot
#        branch: dependabot/${{ steps.date.outputs.today }}
#        committer: Opdrachten Team Dependabot <opdrachten-team-dependabot@amsterdam.nl>
#        commit-message: 'Maintenance run ${{ steps.date.outputs.today }}'

    - uses: someimportantcompany/github-actions-slack-message@v1
      with:
        channel: ${{ inputs.slack_channel }}
        bot-token:  ${{ secrets.SLACK_BOT_TOKEN }}
        text: Firing a bot-token message from Github Actions